from pb.types import *
from os import path, makedirs, listdir

__backpacks__ = [
    Backpack(
        brand_name=("Crumpler", "Year on Year"),
        specs=Specs(h=44, w=31, d=15, V=20, W=800),
        link="https://sg.crumpler.com/products/year-on-year",
        price_sgd=200,
    ),
    Backpack(
        brand_name=("Fjallraven", "Foldsack No. 1"),
        specs=Specs(h=40, w=30, d=15, V=16, W=590),
        link="https://fjallravensea.com/products/foldsack-no-1",
        price_sgd=199,
    ),
    Backpack(
        brand_name=("Cotopaxi", "Allpa 18L Daypack"),
        specs=Specs(h=43, w=28, d=20, V=18, W=630),
        link="https://www.cotopaxi.com/products/allpa-18l-daypack",
        price_sgd=155,
    ),
    Backpack(
        brand_name=("Cotopaxi", "Elqui 18L Daypack"),
        specs=Specs(h=45, w=27, d=19, V=18, W=454),
        link="https://www.cotopaxi.com/products/elqui-18l-daypack",
        price_sgd=103,
    ),
    Backpack(
        brand_name=("Cotopaxi", "Vaya 18L Daypack"),
        specs=Specs(h=48, w=30, d=18, V=18, W=595),
        link="https://www.cotopaxi.com/products/vaya-18l-daypack-cada-dia?variant=39473272422461",
        price_sgd=155,
    ),
    Backpack(
        brand_name=("Goruck", "GR1 USA - Heritage Waxed Canvas"),
        specs=Specs(h=45.7, w=29, d=14, V=21, W=1500),
        link="https://www.goruck.com/en-sg/products/gr1-usa-heritage",
        price_sgd=543,
    ),
    Backpack(
        brand_name=("Cabin Zero", "Classic Pro Backpack 32L"),
        specs=Specs(h=46, w=31, d=20, V=32, W=1235),
        link="https://www.cabinzero.com/products/classic-pro-backpack-32l",
        price_sgd=184,
    ),
    Backpack(
        brand_name=("Patagonia", "Black Hole® Pack 25L"),
        specs=Specs(h=47.8, w=27.9, d=15, V=25, W=640),
        link="https://www.patagonia.com/product/black-hole-pack-25-liters/49298.html?dwvar_49298_color=BKPL",
        price_sgd=192,
    ),
    Backpack(
        brand_name=("Topo Designs", "Rover Pack Classic"),
        specs=Specs(h=43.2, w=27.9, d=11.4, V=20, W=600),
        link="https://topodesigns.com/products/rover-pack",
        price_sgd=140,
    ),
    Backpack(
        brand_name=("MaH", "Young Backpack 13L"),
        specs=Specs(h=38, w=29, d=12, V=13, W=670),
        link="https://www.mah-official.com/products/mah-young-backpack-17",
        price_sgd=84,
    ),
    Backpack(
        brand_name=("Arc'teryx", "Mantis 26"),
        specs=Specs(h=47.5, w=27.5, d=25, V=26, W=840),
        link="https://arcteryx.com/us/en/shop/mantis-26-backpack",
        price_sgd=206,
    ),
    Backpack(
        brand_name=("Crumpler", "Fog"),
        specs=Specs(h=48, w=31.5, d=20.5, V=24, W=950),
        link="https://sg.crumpler.com/products/fog",
        price_sgd=200,
    ),
    Backpack(
        brand_name=("Fjallraven", "Greenland Top"),
        specs=Specs(h=43, w=26, d=15, V=20, W=700),
        link="https://www.fjallraven.com/ca/en-ca/bags-gear/backpacks-bags/laptop-bags/greenland-top/",
        price_sgd=210,
    ),
]


def backpacks():
    bp = list(__backpacks__)
    bp.sort(key=lambda v: v.name)
    bp.sort(key=lambda v: v.specs.W)
    bp.sort(key=lambda v: v.specs.V)
    return bp


def insert(mark_begin: str, mark_end: str, body: str, insert_val: str) -> str:
    pre, mid = body.split(mark_begin, maxsplit=1)
    mid, post = mid.split(mark_end, maxsplit=1)

    pre = pre.strip()
    mid = mid.strip()
    post = post.strip()

    return "\n\n".join((pre, mark_begin, insert_val, mark_end, post))


def markdown_row(values: list[str]) -> str:
    return "|" + "|".join(values) + "|"


def main():
    lines = [markdown_row(Backpack.markdown_header()), "|---|"]
    for b in backpacks():
        lines.append(markdown_row(b.markdown_row()))
        makedirs(b.asset_dir, exist_ok=True)
        makedirs(path.dirname(b.filepath), exist_ok=True)
        with open(b.filepath, "w") as f:
            for pic in sorted(listdir(b.asset_dir)):
                pic_path = path.join("..", b.asset_dir, pic)
                print(f"![]({pic_path})", file=f)

    with open("README.md", "r") as f:
        readme = f.read()

    mark_begin = "<!-- AUTOGENERATED-0 -->"
    mark_end = "<!-- AUTOGENERATED-1 -->"

    readme = insert(mark_begin, mark_end, readme, "\n".join(lines))

    with open("README.md", "w") as f:
        f.write(readme)


if __name__ == "__main__":
    main()
